// <auto-generated />
using System;
using AgendAI.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgendAI.Infra.Persistence.Migrations
{
    [DbContext(typeof(AgendAiDbContext))]
    [Migration("20260602123236_AddTenantsTableAndDefaultSeed")]
    partial class AddTenantsTableAndDefaultSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgendAI.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcedimentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProcedimentoId");

                    b.HasIndex("PacienteId", "Data", "HoraInicio")
                        .IsUnique()
                        .HasDatabaseName("IX_Agendamentos_Paciente_Data_Hora_Agendado")
                        .HasFilter("[Status] = N'agendado'");

                    b.HasIndex("ProfissionalId", "Data", "HoraInicio")
                        .IsUnique()
                        .HasDatabaseName("IX_Agendamentos_Profissional_Data_Hora_Agendado")
                        .HasFilter("[Status] = N'agendado'");

                    b.ToTable("Agendamentos", (string)null);
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.Atendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgendamentoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Dentes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean");

                    b.Property<int?>("Parcelas")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProcedimentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Retorno")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId")
                        .IsUnique()
                        .HasDatabaseName("IX_Atendimentos_AgendamentoId")
                        .HasFilter("[AgendamentoId] IS NOT NULL");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProcedimentoId");

                    b.HasIndex("ProfissionalId", "Data", "Hora")
                        .IsUnique()
                        .HasDatabaseName("IX_Atendimentos_Profissional_Data_Hora");

                    b.ToTable("Atendimentos", (string)null);
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.BloqueioAgenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalId");

                    b.ToTable("BloqueiosAgenda", (string)null);
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.ChamadaPainelTvAtual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AgendamentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Horario")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("PacienteNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProfissionalNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PainelTvChamadaAtual", (string)null);
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.ConfiguracaoClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("HoraAbertura")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraFechamento")
                        .HasColumnType("time without time zone");

                    b.Property<int>("IntervaloMinutos")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesClinica", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoraAbertura = new TimeOnly(8, 0, 0),
                            HoraFechamento = new TimeOnly(18, 0, 0),
                            IntervaloMinutos = 30,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AtendimentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Paciente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Procedimento")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Profissional")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId")
                        .IsUnique()
                        .HasDatabaseName("IX_Lancamentos_AtendimentoId")
                        .HasFilter("[AtendimentoId] IS NOT NULL");

                    b.ToTable("Lancamentos", (string)null);
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoSanguineo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_Pacientes_Cpf");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.PacienteAnamnese", b =>
                {
                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("AlergiaMaterialDesc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AlergiaMedicamentoDesc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstaGravida")
                        .HasColumnType("boolean");

                    b.Property<bool>("Fumante")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicamentoContinuoDesc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ObservacoesGerais")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("TemAlergiaMaterial")
                        .HasColumnType("boolean");

                    b.Property<bool>("TemAlergiaMedicamento")
                        .HasColumnType("boolean");

                    b.Property<bool>("TemCoagulopatia")
                        .HasColumnType("boolean");

                    b.Property<bool>("TemDiabetes")
                        .HasColumnType("boolean");

                    b.Property<bool>("TemDoencaCardiaca")
                        .HasColumnType("boolean");

                    b.Property<bool>("TemHipertensao")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("UsaMedicamentoContinuo")
                        .HasColumnType("boolean");

                    b.HasKey("PacienteId");

                    b.ToTable("PacienteAnamneses", (string)null);
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.PacienteHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Procedimento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Profissional")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("PacienteHistoricos", (string)null);
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.Procedimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Procedimentos", (string)null);
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Tenants_Slug");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.TokenRecuperacaoSenha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Utilizado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokensRecuperacaoSenha", (string)null);
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_Email")
                        .HasFilter("\"Email\" IS NOT NULL AND \"Email\" <> ''");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_Login");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("AgendAI.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendAI.Domain.Entities.Procedimento", "Procedimento")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ProcedimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendAI.Domain.Entities.Usuario", "Profissional")
                        .WithMany("AgendamentosComoProfissional")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Procedimento");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.Atendimento", b =>
                {
                    b.HasOne("AgendAI.Domain.Entities.Agendamento", "Agendamento")
                        .WithOne("Atendimento")
                        .HasForeignKey("AgendAI.Domain.Entities.Atendimento", "AgendamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgendAI.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Atendimentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendAI.Domain.Entities.Procedimento", "Procedimento")
                        .WithMany("Atendimentos")
                        .HasForeignKey("ProcedimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendAI.Domain.Entities.Usuario", "Profissional")
                        .WithMany("AtendimentosComoProfissional")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agendamento");

                    b.Navigation("Paciente");

                    b.Navigation("Procedimento");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.BloqueioAgenda", b =>
                {
                    b.HasOne("AgendAI.Domain.Entities.Usuario", "Profissional")
                        .WithMany("BloqueiosAgenda")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.Lancamento", b =>
                {
                    b.HasOne("AgendAI.Domain.Entities.Atendimento", "Atendimento")
                        .WithOne("Lancamento")
                        .HasForeignKey("AgendAI.Domain.Entities.Lancamento", "AtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.PacienteAnamnese", b =>
                {
                    b.HasOne("AgendAI.Domain.Entities.Paciente", "Paciente")
                        .WithOne("Anamnese")
                        .HasForeignKey("AgendAI.Domain.Entities.PacienteAnamnese", "PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.PacienteHistorico", b =>
                {
                    b.HasOne("AgendAI.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Historicos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.TokenRecuperacaoSenha", b =>
                {
                    b.HasOne("AgendAI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("TokensRecuperacaoSenha")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.Agendamento", b =>
                {
                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.Atendimento", b =>
                {
                    b.Navigation("Lancamento");
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Anamnese");

                    b.Navigation("Atendimentos");

                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.Procedimento", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Atendimentos");
                });

            modelBuilder.Entity("AgendAI.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AgendamentosComoProfissional");

                    b.Navigation("AtendimentosComoProfissional");

                    b.Navigation("BloqueiosAgenda");

                    b.Navigation("TokensRecuperacaoSenha");
                });
#pragma warning restore 612, 618
        }
    }
}
