// <auto-generated />
using AgendAI.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AgendAI.Infra.Persistence.Migrations
{
    [DbContext(typeof(AgendAiDbContext))]
    [Migration("20260528153000_AddPainelTvProfissionalVinculo")]
    partial class AddPainelTvProfissionalVinculo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
